(function () {
  window.Blazzlers = window.Blazzlers || {};

  Object.assign(window.Blazzlers, {
    MAX_CANVAS_RESOLUTION: 5120,
    MIN_WORLD_WIDTH: 280,
    MIN_WORLD_HEIGHT: 280,
    INITIAL_RADIUS: 20,
    INITIAL_PER_RACE: 6,
    INITIAL_RADIUS_VARIATION: 0.02,
    REPRODUCTION_CHANCE: 0.2,
    DECAY_CHANCE: 0.1,
    DECAY_AVERAGE_SIZE_RATIO: 1.5,
    DECAY_MIN_RADIUS: 24,
    DECAY_MIN_FRAGMENT_RADIUS: 6,
    MAX_DELTA_SECONDS: 0.05,
    DEFAULT_SPEED_MULTIPLIER: 100,
    SPEED_STEP_RATIO: 1.1,
    REPRODUCTION_COOLDOWN_SECONDS: 0.8,
    CHARGE_STRENGTH: 0.25,
    CHARGE_RANGE: 420,
    MIN_CHARGE_DISTANCE: 48,
    MAX_DIRECTION_FORCE: 100,
    ORBITAL_SWIRL_STRENGTH: 0.55,
    BLACK_HOLE_RADIUS_RATIO: 1.8,
    AUTO_RESTART_SECONDS: 5,
    READY_COUNTDOWN_SECONDS: 3,
  });
}());
